// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaFvO2MFV8WvifC7FQT_B0GkQ2rDw8oOA',
    appId: '1:1071976384054:web:56a23339df740b65edba97',
    messagingSenderId: '1071976384054',
    projectId: 'fypconnect-19dfd',
    authDomain: 'fypconnect-19dfd.firebaseapp.com',
    storageBucket: 'fypconnect-19dfd.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-lcM8btHKZv2yuyTebd4r0e5-CrT6ZEI',
    appId: '1:1071976384054:ios:f4baddc2bd0fdb68edba97',
    messagingSenderId: '1071976384054',
    projectId: 'fypconnect-19dfd',
    storageBucket: 'fypconnect-19dfd.firebasestorage.app',
    iosBundleId: 'com.example.fypConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaFvO2MFV8WvifC7FQT_B0GkQ2rDw8oOA',
    appId: '1:1071976384054:web:d61c9cd44fcf7cf1edba97',
    messagingSenderId: '1071976384054',
    projectId: 'fypconnect-19dfd',
    authDomain: 'fypconnect-19dfd.firebaseapp.com',
    storageBucket: 'fypconnect-19dfd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-lcM8btHKZv2yuyTebd4r0e5-CrT6ZEI',
    appId: '1:1071976384054:ios:f4baddc2bd0fdb68edba97',
    messagingSenderId: '1071976384054',
    projectId: 'fypconnect-19dfd',
    storageBucket: 'fypconnect-19dfd.firebasestorage.app',
    iosBundleId: 'com.example.fypConnect',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhQw6Q1APpHclZm_KaIJNHzBy0RN7R0KE',
    appId: '1:1071976384054:android:aac5c0ce10564007edba97',
    messagingSenderId: '1071976384054',
    projectId: 'fypconnect-19dfd',
    storageBucket: 'fypconnect-19dfd.firebasestorage.app',
  );

}